### ISSUE TITLE
Could not find name `__doc__` [unknown-name]

### ISSUE THREAD

**Issue by AA-Turner** [facebook/pyrefly#285]
### Describe the Bug

pyrefly doesn't seem to recognise the module `__doc__` variable.

A

### Sandbox Link

https://pyrefly.org/sandbox/?code=EQgmHsGMGcBcCcCWA7A5iYAoTB9ABALx444SQmZA

**Comment by ndmitchell** [comment]
Thanks for the bug report, I've got a fix I'm just testing.

**Comment by AA-Turner** [comment]
I've reported a few errors from running `pyrefly` on Sphinx, but currently there's just under 1,000 so hard to pick out which are the most relevant!

A

**Comment by ndmitchell** [comment]
Thanks for the reports! They're certainly useful so far. Is it just a case of check out Sphinx and run Pyrefly or were you doing anything else? That way we can reproduce and go through them (although we very much appreciate any you raise, especially with your reduced test cases).

**Comment by AA-Turner** [comment]
@ndmitchell yes, see below for a `uv`-based quickstart:

```console
$ git clone https://github.com/sphinx-doc/sphinx && cd sphinx
$ uv venv && . .venv/bin/activate
$ uv pip install -e . --group package --group test --group types pyrefly
$ pyrefly check 
```

I've also disabled the `implicitly-defined-attribute` warning as it's very noisy in Sphinx.

```toml
# pyrefly.toml
project_includes = [
    "doc/conf.py",
    "doc/development/tutorials/examples/autodoc_intenum.py",
    "doc/development/tutorials/examples/helloworld.py",
    "sphinx",
    "tests",
    "utils",
]
project_excludes = ["**/tests/roots*"]
python_version = "3.11.0"
replace_imports_with_any = ["imagesize", "pyximport", "snowballstemmer"]

[errors]
implicitly-defined-attribute = false
```

Running `pyrefly check sphinx` gets ~770 errors, running `pyrefly check` gets ~1.5k.

A
