### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by nth10sd** [facebook/pyrefly#383]
### Describe the Bug

`mypy` has strict mode, and `pyright` / `basedpyright` also have various modes (e.g. "strict", "standard"). Will pyrefly consider having this as well?

This is to account for different preferences in the level of strictness for type checkers.

**Comment by ndmitchell** [comment]
Yes! We plan to have a strict mode.

We're still figuring out exactly what it should do. But my broad thinking is:

* Gradual: Everything gets inferred to be Any. You rarely get a type error without an annotation.
* Standard: We infer return types and list types.
* Strict: We error if we can't infer with reasonable precision (e.g. if we infer an Any).

**Comment by rchen152** [comment]
Merging https://github.com/facebook/pyrefly/issues/1295 into this issue. Some things we'll likely want in strict mode:
* `implicit-any` (see https://github.com/facebook/pyrefly/commit/a01efe55997c6ec89417c367b58ab337725fd133 and https://github.com/facebook/pyrefly/commit/e6eaf1f06df0c908ae3b9bfac9fd4c908e74fe70).
* Error on unpacking an open TypedDict into another TypedDict (see https://github.com/facebook/pyrefly/issues/1351#issuecomment-3464392546).
* (maybe) Downgrade more lint-like errors like redundant-condition, bad-dunder-all, and unreachable to warn by default and set them to error in strict mode

**Comment by DanielNoord** [comment]
Is there currently a way to make all diagnostics have the `error` severity? If I read the [docs](https://pyrefly.org/en/docs/configuration/#errors) correctly I'd need to enumerate them all individually, but at least for now I'd like to just get a warning on every diagnostic (or lint) `pyrefly` finds.

**Comment by yangdanny97** [comment]
There isn't currently a way to do that, but I'd be open to suggestions for how to allow that. Maybe the solution is just strict mode, maybe there's another way

For now, you wouldn't necessarily need to enumerate _every_ single error code, just the ones that don't default to the "error" severity. The list of defaults is here:

https://github.com/facebook/pyrefly/blob/5cb4611765e8caf4b740dfc630b3b267b2dd69ae/crates/pyrefly_config/src/error_kind.rs#L321

**Comment by jorenham** [comment]
FWIW, scipy-stubs uses the following config-combo:

```toml

[tool.pyrefly]
enabled-ignores = ["pyrefly"]

[tool.pyrefly.errors]
implicit-abstract-class = "error"
implicit-any = "error"
implicitly-defined-attribute = "error"
missing-override-decorator = "error"
not-required-key-access = "error"
open-unpacking = "error"
unannotated-attribute = "error"
unannotated-parameter = "error"
unannotated-return = "error"
untyped-import = "error"
unused-ignore = "error"
variance-mismatch = "error"
```

but maybe that's a bit *too* strict 😛
