### ISSUE TITLE
project_includes and project_excludes are not respected in pyproject.toml

### ISSUE THREAD

**Issue by indoyoon** [facebook/pyrefly#404]
### Describe the Bug

Hi, I would like to apply those rules:

```toml
[tool.pyrefly]
project_includes = ["src1", "src2"]
project_excludes = ["**/.[!/.]*", "**/*venv/**", "tests"]
```

however, running `pyrefly check` still checks a folder "tests". Also it seems it checks folders not listed in `project_includes`. It correctly loads settings from the `pyproject.toml`.

```bash
pyrefly check
INFO Checking project configured at `/project/pyproject.toml`
```

Why this setting is overriden when I didn't provide CLI parameters? Thanks.

### (Only applicable for extension issues) IDE Information

MacOS Zed, remote linux environment

**Comment by lolpack** [comment]
I wonder if the logic for how pyrefly is initialized in zed is related: https://github.com/zed-extensions/pyrefly/blob/main/src/pyrefly.rs

**Comment by indoyoon** [comment]
I highly doubt that because I am running Pyrefly from the terminal, and I even don't have Pyrefly Zed extension installed.

**Comment by connernilsen** [comment]
Hey @indoyoon, I have a few questions for you that will help me narrow in on what's going on:
- Is this the whole Pyrefly part of your config?
```
[tool.pyrefly]
project_includes = ["src1", "src2"]
project_excludes = ["**/.[!/.]*", "**/*venv/**", "tests"]
```
- How are you running Pyrefly? What's the exact command, and which directory are you executing this from relative to the config that's being found?
- Where is the `tests` folder relative to the config that's being found? Also, where are the directories that are being included that aren't specified in your config relative to the config?

**Comment by indoyoon** [comment]
1. I have other rules like `replace_imports_with_any` and `[[tool.pyrefly.sub_config]]`.
2. Litterally `pyrefly check` is the whole thing I'm trying to use. `pyproject.toml` is located at the project's root, and I'm invoking the command at the same location.
3. Here you go:
```
.
├── src1
├── src2
├── tests
├── venv
└── pyproject.toml
```

**Comment by connernilsen** [comment]
@indoyoon More questions:

1. Which version of Pyrefly are you running? (`pyrefly --version`)
2. Can you attach the first few lines of `pyrefly check --verbose` (before the errors start)?

**Comment by indoyoon** [comment]
### 1

From `pyproject.toml`

```
"pyrefly==0.17.1",
```

```
$ pyrefly --version
pyrefly 0.17.1
```

### 2

```
 INFO Checking project configured at `/project/pyproject.toml`
DEBUG Config is: {project_includes: [/project/**/*], project_excludes: [/project/**/.[!/.]*, /project/**/*venv/**/*], search_path: [/project/], python_interpreter: None, python_environment: {python_platform: linux, python_version: 3.13.1, site_package_path: [/.pyenv/versions/3.13.1/lib/python3.13, /.pyenv/versions/3.13.1/lib/python3.13/lib-dynload, /project/venv/lib/python3.13/site-packages, __editable__.project-0.97.0.dev51+g6295b0b6e.d20250522.finder.__path_hook__], site_package_path_source: Interpreter("/project/venv/bin/python3.13")}, replace_imports_with_any: []}
DEBUG Checking 906 files (listing took 0.93s)
```

**Comment by connernilsen** [comment]
@indoyoon interesting, it looks like Pyrefly is finding your configuration, but not reading it at all. I wonder if there's some kind of parse error going on.

Do you see anything like this in your output?
```
ERROR /project/pyproject.toml: TOML parse error at line X, column Y
```

If not, would you be open to sharing your `pyproject.toml` here so that I can see if there's anything else going on that might be causing this? Otherwise, I can try to see if there's anything in the rest of your `pyrefly check --verbose` output that might indicate what else might be going on, but the `pyproject.toml` part might be the most helpful.

If it's something you can't share online, we could do a video call through our Discord server where I can take a more direct look at what's going on.

**Comment by indoyoon** [comment]
Even if I remove all other settings, it is still the same. 

```toml
[build-system]
requires = [
  "setuptools~=80.0",
  "setuptools_scm~=8.0",
]

[project]
name="ds"
authors = [
    {name = "Team", email = "ran@dom.corp"},
]
description="Core"
requires-python =">=3.9, <3.14"
dynamic = ["version"]
dependencies = [
    "tqdm~=4.60",
]


[tool.pyrefly]
project_includes = ["src1", "src2"]
project_excludes = ["**/.[!/.]*", "**/*venv/**", "**/tests/**/*.py"]

replace_imports_with_any = [
  "docker.*",
  "google.auth.*",
  "sqlakeyset.*",
  "google.cloud.*",
  "kubernetes.*",
  "pygerrit2.*",
  "httpie.*",
  "jwcrypto.*",
  "google",
]

[tool.pyrefly.errors]
possibly-undefined = true
explicit-override = true
ignore-without-code = true
```

Meanwhile I will test this in the different machines
