### ISSUE TITLE
Documentation: Put Pyrefly in your CI

### ISSUE THREAD

**Issue by lolpack** [facebook/pyrefly#8]
Survey the top CI platforms with instructions and links appropriately: circleci, github etc...

**Comment by benglewis** [comment]
It would be great if a GitHub Action workflow were to exist for this tool :)
It always helps ensure that tools are used properly in CI when they have an official workflow

**Comment by lolpack** [comment]
Hi @benglewis, thanks for reaching out. We plan to have a GitHub action at some point which can add additional features for CI. For now using the standard Python GitHub flows will appropriately fail the workflow if errors are found. Here is an example that works today: https://github.com/zsol/dotslash-python/pull/8/files

```
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install pyrefly
      - name: Typecheck
        run: pyrefly check
```
